### ISSUE TITLE
Serve API from /api route

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/pelias-canada#36]
It'd be good to serve the api from `/api` and the ui from `/`.
The result would be `https://geocoder.alpha.phac.gc.ca/api/v1/search?text=%22579%20Dundonald%20Dr.,%20Ottawa,%20ON%22`

**Comment by simardeep1792** [comment]
Fixed.

API: https://geocoder.alpha.phac.gc.ca/api/search?text=%22579%20Dundonald%20Dr.,%20Ottawa,%20ON%22 
UI: https://geocoder.alpha.phac.gc.ca
