### ISSUE TITLE
Separate pages for introductory blurb and Python and R code examples. 

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/pelias-canada#38]
Once we get #31 in place we'll want to expand this with a Python example and doing that requires some reorganization:
We'll want to make some separate pages:

- **default page**: introductory blurb explaining value
- **python page**: reasonable python example (probably using [requests](https://pypi.org/project/requests/))
- **R page**: reasonable R example (probably using [jsonlite](https://cran.r-project.org/web/packages/jsonlite/vignettes/json-apis.html))

These pages make some obvious extension points for some more "app-like" behavior we've been talking about later on.

**Comment by GRaganold** [comment]
Using React-router-dom we can create these pages. 

there is a Pull Request which adds the menu where links are set to "#".
