### ISSUE TITLE
Replace date modified with a version.

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/pelias-canada#50]
The application [currently uses](https://github.com/PHACDataHub/pelias-canada/blob/86614b55d8b73e791e052f8323c8c893b55adc9e/ui/src/layout/layout.jsx#L37) the [Date Modified component](https://design-system.alpha.canada.ca/en/components/date-modified/). That is fine for a static site but doesn't make a lot of sense for a web application and should be replaced with a version which would just be the [image tag](https://github.com/PHACDataHub/pelias-canada/blob/86614b55d8b73e791e052f8323c8c893b55adc9e/ui/cloudbuild.yaml#L11) (not the full image name) when the image is [built](https://github.com/PHACDataHub/pelias-canada/blob/86614b55d8b73e791e052f8323c8c893b55adc9e/ui/cloudbuild.yaml#L24).

That would require the [injection of a env var into the rspack build process](https://rsbuild.dev/guide/advanced/env-vars).

**Comment by GRaganold** [comment]
Would we want to look into using the commit API for this :

https://api.github.com/repos/PHACDataHub/pelias-canada

https://api.github.com/repos/PHACDataHub/pelias-canada/commits

**Comment by GRaganold** [comment]
If we are doing versioning, we may want to have someone keep at this @sleepycat 

https://docs.github.com/en/contributing/writing-for-github-docs/versioning-documentation
