### ISSUE TITLE
Keep API version in URL

### ISSUE THREAD

**Issue by sleepycat** [PHACDataHub/pelias-canada#62]
Pelias already includes the API version in the URL.
We are redirecting to `/api` but it'd be good to ensure the version is still visible.
Previous: `https://geocoder.alpha.phac.gc.ca/v1/search?text=london`
Current: `https://geocoder.alpha.phac.gc.ca/api/search?text=london`
Ideal: `https://geocoder.alpha.phac.gc.ca/api/v1/search?text=london`

[The example code](https://github.com/PHACDataHub/pelias-canada/blob/a2578fe5d5188a8dbe3d4686f353fc24defe7d24/ui/src/pages/landingPage/Ladingpage.jsx#L18) will need to be updated to reflect this change as well.

**Comment by simardeep1792** [comment]
@sleepycat, the changes have been made and the service is up and running. The UI has also been updated to reflect these changes. It's ready for your review.

Bumping @GRaganold @NickZachary
